platform :ios, '16.0'
require_relative '../node_modules/react-native/scripts/autolink-ios'

target 'AppBlocker' do
  config = use_native_modules!

  use_frameworks!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    :fabric_enabled => false
  )

  target 'AppBlockerTests' do
    inherit! :complete
  end
end
